parameters:
  youzan_api.default_kdt_id: '%env(string:default::YOUZAN_DEFAULT_KDT_ID)%'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  YouzanApiBundle\Repository\:
    resource: '../../Repository/'
  YouzanApiBundle\Service\:
    resource: '../../Service/'
  YouzanApiBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  YouzanApiBundle\Service\AdminMenu:
    public: true

  YouzanApiBundle\Service\YouzanClientService:
    arguments:
      $defaultKdtId: '%youzan_api.default_kdt_id%'
